export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  BATCH_ALREADY_MERGED: "BATCH_ALREADY_MERGED",
  CONFLICT_UNRESOLVED: "CONFLICT_UNRESOLVED",
  NO_CONFLICT_TO_RESOLVE: "NO_CONFLICT_TO_RESOLVE",
  BASELINE_CHANGED: "BASELINE_CHANGED",
  MERGE_FAILED: "MERGE_FAILED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND"
} as const;
