export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  CONFLICT_NOT_FOUND: "CONFLICT_NOT_FOUND",
  CONFLICT_ALREADY_RESOLVED: "CONFLICT_ALREADY_RESOLVED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  UNRESOLVED_CONFLICT: "UNRESOLVED_CONFLICT",
  MERGE_FAILED: "MERGE_FAILED"
} as const;
